# Material Dark Theme for Kitty
# https://github.com/kovidgoyal/kitty-themes

background            #222221
foreground            #e4e4e4
cursor                #16aec9
selection_background  #dedede
selection_foreground  #222221

# Black
color0                #212121
color8                #424242

# Red
color1                #b7141e
color9                #e83a3f

# Green
color2                #457b23
color10               #7aba39

# Yellow
color3                #f5971d
color11               #fee92e

# Blue
color4                #134eb2
color12               #53a4f3

# Magenta
color5                #550087
color13               #a94dbb

# Cyan
color6                #0e707c
color14               #26bad1

# White
color7                #eeeeee
color15               #d8d8d8

# Tab bar colors
active_tab_foreground   #444444
active_tab_background   #dedede
inactive_tab_foreground #e4e4e4
inactive_tab_background #1b1b1a
