# Font Configuration

font_family      JetBrains Mono
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic
font_size        13.0

# Font features
disable_ligatures never
font_features none

# Adjust line height for better readability
modify_font cell_height 110%
