# Keyboard Shortcuts

kitty_mod cmd

# Clipboard
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+shift+v paste_from_selection

# Window management
map cmd+n new_os_window
map cmd+w close_window
map cmd+enter new_window
map cmd+] next_window
map cmd+[ previous_window
map cmd+shift+] move_window_forward
map cmd+shift+[ move_window_backward

# Tab management
map cmd+t new_tab
map cmd+shift+w close_tab
map cmd+shift+right next_tab
map cmd+shift+left previous_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# Layout management
map cmd+l next_layout
map cmd+shift+l previous_layout

# Font sizes
map cmd+equal     change_font_size all +1.0
map cmd+minus     change_font_size all -1.0
map cmd+0         change_font_size all 0

# Scrolling
map cmd+k clear_terminal scrollback active
map cmd+shift+k clear_terminal reset active
map cmd+up scroll_line_up
map cmd+down scroll_line_down
map cmd+page_up scroll_page_up
map cmd+page_down scroll_page_down
map cmd+home scroll_home
map cmd+end scroll_end

# Miscellaneous
map cmd+, edit_config_file
map cmd+shift+, load_config_file
map cmd+f launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i

# Open URL in browser
map cmd+shift+o open_url_with_hints
