# macOS Specific Settings

# Title bar
hide_window_decorations titlebar-only
macos_titlebar_color background
macos_option_as_alt no
macos_quit_when_last_window_closed yes
macos_show_window_title_in window

# Font rendering
macos_thicken_font 0.1

# Display
macos_traditional_fullscreen no
macos_custom_beam_cursor yes
macos_colorspace displayp3
